name: RLI continuous integration
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - run: pip install -Ur requirements.txt
      - run: pip install -e .

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - run: pip install -Ur requirements.txt
      - run: black --check setup.py rli/

  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - run: pip install -Ur requirements.txt
      - run: pytest -n 2 tests
      - uses: warchant/setup-sonar-scanner@v1
      - run: sonar-scanner -X
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.branch.name=${GITHUB_REF##*/}
          -Dsonar.projectVersion=$(git rev-parse --short "$GITHUB_SHA")
          -Dsonar.host.url=https://sonarcloud.io/
          -Dsonar.organization=luke-shay
          -Dsonar.projectKey=rli
          -Dsonar.projectName=rli
          -Dsonar.sources=rli/
          -Dsonar.tests=tests/
          -Dsonar.exclusions=**/cli.py,**/cmd_smoke.py
          -Dsonar.python.xunit.reportPath=test_output/test-report.xml
          -Dsonar.python.coverage.reportPaths=test_output/coverage.xml
